#! /usr/bin/env perl

# Converts the Makefile buildtargets to a cmake format.
#
#    ./cmakify_buildtarget.pl < Makefile > cmake/buildtarget.cmake
#
# It only processes these variables:
#
# |  Make variable     | CMake variables                                                       |
# | ------------------ | --------------------------------------------------------------------- |
# | FC_PARALLEL        | FC and CMAKE_Fortran_COMPILER                                         |
# | CXX_PARALLEL       | CXX and CMAKE_CXX_COMPILER                                            |
# | CC_PARALLEL        | CC and CMAKE_C_COMPILER                                               |
# | FFLAGS_OPT         | appended to CMAKE_Fortran_FLAGS_RELEASE                               |
# | CFLAGS_OPT         | appended to CMAKE_C_FLAGS_RELEASE                                     |
# | CXXFLAGS_OPT       | appended to CMAKE_CXX_FLAGS_RELEASE                                   |
# | FFLAGS_DEBUG       | appended to CMAKE_Fortran_FLAGS_DEBUG                                 |
# | CFLAGS_DEBUG       | appended to CMAKE_C_FLAGS_DEBUG                                       |
# | CXXFLAGS_DEBUG     | appended to CMAKE_CXX_FLAGS_DEBUG                                     |
# | FFLAGS_PROMOTION   | appended to CMAKE_Fortran_FLAGS_RELEASE and CMAKE_Fortran_FLAGS_DEBUG |
#
# The resulting cmake code chooses the build target which matches the CMake `BUILDTARGET` variable.
# If none match, it aborts with an error (via `message( FATAL_ERROR ...)`).
# The default option for `BUILDTARGET` must be one that exists in the Makefile.

$in_build_target = 0;

print("# This file was automatically generated by cmakify_buildtarget.pl.\n");
print("\n");

$known = "Valid build targets: ";

while(<>) {
    chomp;
    # Find lines like:
    #     cray: # BUILDTARGET Cray Programming Environment
    if(/^(\S+):(\s*#.*$)?/) {
        $buildtarget = $1; # like "cray"
        if($in_build_target) {
            print("elseif(BUILDTARGET STREQUAL \"$buildtarget\")$2\n")
        } else {
            print("if(BUILDTARGET STREQUAL \"$buildtarget\")$2\n")
        }
        $in_build_target = 1;
        print("  message(\"Using compiliation options for build target \\\"$buildtarget\\\"\")\n");
        $known .= "$buildtarget ";

    } elsif($in_build_target and /^\t"FC_PARALLEL\s*=\s*(.*?)"/) {
        print("  set(CMAKE_Fortran_COMPILER \"$1\")\n");
        print("  set(FC \"$1\")\n");

    } elsif($in_build_target and /^\t"CXX_PARALLEL\s*=\s*(.*?)"/) {
        print("  set(CMAKE_CXX_COMPILER \"$1\")\n");
        print("  set(CXX \"$1\")\n");

    } elsif($in_build_target and /^\t"CC_PARALLEL\s*=\s*(.*?)"/) {
        print("  set(CMAKE_C_COMPILER \"$1\")\n");
        print("  set(CC \"$1\")\n");

    } elsif($in_build_target and /^\t"FFLAGS_OPT\s*=\s*(.*?)"/) {
        print("  set(CMAKE_Fortran_FLAGS_RELEASE \"\${CMAKE_Fortran_FLAGS_RELEASE} $1\")\n");

    } elsif($in_build_target and /^\t"CFLAGS_OPT\s*=\s*(.*?)"/) {
        print("  set(CMAKE_C_FLAGS_RELEASE \"\${CMAKE_C_FLAGS_RELEASE} $1\")\n");

    } elsif($in_build_target and /^\t"CXXFLAGS_OPT\s*=\s*(.*?)"/) {
        print("  set(CMAKE_CXX_FLAGS_RELEASE \"\${CMAKE_CXX_FLAGS_RELEASE} $1\")\n");

    } elsif($in_build_target and /^\t"FFLAGS_DEBUG\s*=\s*(.*?)"/) {
        print("  set(CMAKE_Fortran_FLAGS_DEBUG \"\${CMAKE_Fortran_FLAGS_DEBUG} $1\")\n");

    } elsif($in_build_target and /^\t"CFLAGS_DEBUG\s*=\s*(.*?)"/) {
        print("  set(CMAKE_C_FLAGS_DEBUG \"\${CMAKE_C_FLAGS_DEBUG} $1\")\n");

    } elsif($in_build_target and /^\t"CXXFLAGS_DEBUG\s*=\s*(.*?)"/) {
        print("  set(CMAKE_CXX_FLAGS_DEBUG \"\${CMAKE_CXX_FLAGS_DEBUG} $1\")\n");

    } elsif($in_build_target and /^\t"FFLAGS_PROMOTION\s*=\s*(.*?)"/) {
        print("  if(MPAS_PRECISION STREQUAL double)\n");
        print("    set(CMAKE_Fortran_FLAGS_RELEASE \"\${CMAKE_Fortran_FLAGS_RELEASE} $1\")\n");
        print("    set(CMAKE_Fortran_FLAGS_DEBUG \"\${CMAKE_Fortran_FLAGS_DEBUG} $1\")\n");
        print("  endif()\n");


    } elsif(/^\S.*=/ and $in_build_target) {
        # End of BUILDTARGET list.
        print("else()\n");
        print("  message( FATAL_ERROR \"Aborting due to invalid build target \\\"\${BUILDTARGET}\\\". $known\" )\n");
        print("endif()\n");
        last;
    }
}
