name: CI test to build MPAS Standalone

on: [pull_request,workflow_dispatch,push]

jobs:
  build_mpas:

    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        fortran-compiler: [gfortran-10, gfortran-11, gfortran-12]

    # Environmental variables
    env:
      NFHOME:      /usr
      NFVERSION:   v4.5.3
      driver_ROOT: /home/runner/work/template/template

    # Workflow steps
    steps:

    - name: Checkout code (into ${driver_ROOT})
      uses: actions/checkout@v3

    # NetCDF C and FORTRAN libraries
    - name: Install NetCDF library
      run: |
        sudo apt-get update
        sudo apt-get install libnetcdff-dev

    - name: Cache openmpi
      id: cache-openmpi
      uses: actions/cache@v4
      with:
        path: /home/runner/ompi-4.1.6
        key: cache-openmpi-${{matrix.fortran-compiler}}-key

    - name: Install openmpi
      if: steps.cache-openmpi.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/open-mpi/ompi/archive/refs/tags/v4.1.6.tar.gz
        tar -xvf v4.1.6.tar.gz
        cd ompi-4.1.6
        ./autogen.pl
        ./configure --prefix=/home/runner/ompi-4.1.6
        make -j4
        make install
        echo "LD_LIBRARY_PATH=/home/runner/ompi-4.1.6/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PATH=/home/runner/ompi-4.1.6/bin:$PATH" >> $GITHUB_ENV

    # PNetCDF library

    # PIO library

    # Download any dependencies?

    # Build MPAS-A 