name: Run MPAS Standalone (NOAA GSL tests)

on: [push, pull_request, workflow_dispatch]

#############################################################################################
# Testing script/workflow for ufs-community fork of MPAS-Dev/MPAS-A.
#
# Description (outside of software stack setup (Step 0))
#
# - Clone and build MPAS for baseline generation.
# - Clone and build MPAS for feature branch testing (against baselines).
# - Clone ufs-community MPAS testing repository.
# - Fetch data from THREDDS server.
# - Donwload any other data (e.g. MP tables, etc).
# - Create/populate MPAS run directories.
# - Run MPAS using baseline codebase/configuration.
# - Run MPAS using feature branch.
# - Compare results.
# - Save output files to GitHub artifact (for comparision w/ inline/standaloen results)
#
# Comments:
# - The test build/run configurations matrix is described below.
# - This script uses a matrix run configuration with exclusions to achieve the desired "run list"
#
# <physics> - List of physics configuration to test. See https://github.com/barlage/mpas_testcase.git
# <repo>    - Baseline codebase repository.
# <branch>  - Baseline codebase repository branch.
#
# Tests:
#        Baseline Codebase Repository:Branch   Physics                       build type
# 1/7)   MPAS-Dev:v8.3.0                       mesoscale_reference           Release/Debug
# 2/8)   MPAS-Dev:v8.3.0                       convection_permitting         Release/Debug
# 3/9)   MPAS-Dev:v8.3.0                       mesoscale_reference_noahmp    Release/Debug
# 4/10)  ufs-community:gsl/develop             mesoscale_reference           Release/Debug
# 5/11)  ufs-community:gsl/develop             convection_permitting         Release/Debug
# 6/12)  ufs-community:gsl/develop             mesoscale_reference_noahmp    Release/Debug
#
#############################################################################################
jobs:
  run_mpas:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false  # Disable fail-fast
      matrix:
        f-compiler: [gfortran]#,ifx]#, nvfortran]
        physics:    [mesoscale_reference]#, convection_permitting, mesoscale_reference_noahmp]
        repo:       [ufs-community]#, MPAS-Dev]
        branch:     [gsl/develop]#, v8.3.0]
        build-type: [Release]#, Debug]
        exclude:
          - repo: MPAS-Dev
            branch: gsl/develop
          - repo: ufs-community
            branch: v8.3.0
        include:
        # Set container images for each compiler
        - f-compiler: gfortran
          bld_target: gfortran
          image: dustinswales/ufs-community-mpas-ci:gnu
#        - f-compiler: ifx
#          image: dustinswales/ufs-community-mpas-ci:oneapi
#          bld_target: intel
#        - f-compiler: nvfortran
#          image: dustinswales/ccpp-scm-ci:nvhpc
    container:
      image: ${{ matrix.image }}
    # 
    defaults:
      run:
        shell: bash -el {0}

    # Environmental variables
    env:
      py-version:        3.11
      runner_ROOT:       /__w/
      MPAS_ROOT:         /__w/MPAS-Model/MPAS-Model
      mpas_bl_ROOT:      /__w/MPAS-Model-BL
      PNETCDF:           /opt/pnetcdf
      mpas_ics:          testing_and_setup/ufs-community/data/ics/mpasdev.gfs.winter
      ic_source:         gfs

    # Workflow steps
    steps:

    ##########################################################################################
    # Step 0: Setup
    ##########################################################################################
    - name: Setup MPI (GNU)
      if: matrix.f-compiler == 'gfortran'
      run: |
        echo "CC=mpicc"   >> $GITHUB_ENV
        echo "CXX=mpicxx" >> $GITHUB_ENV
        echo "FC=mpif90"  >> $GITHUB_ENV

    - name: Setup MPI (Intel OneAPI)
      if: matrix.f-compiler == 'ifx'
      run: |
        echo "PATH=/opt/intel/oneapi/mpi/latest/bin:${PATH}" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=/opt/intel/oneapi/mpi/latest/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
        echo "CC=mpiicx"   >> $GITHUB_ENV
        echo "CXX=mpiicpx" >> $GITHUB_ENV
        echo "FC=mpiifx"   >> $GITHUB_ENV
        echo "MPICC=/opt/intel/oneapi/mpi/latest/bin/mpiicx"   >> $GITHUB_ENV

    - name: Setup PnetCDF
      run: |
        echo "PNETCDF=/opt/pnetcdf"   >> $GITHUB_ENV

    ##########################################################################################
    # Step 1: Setup configuration for current test
    ##########################################################################################
    - name: Configuration for MPAS-Dev (baseline) tests.
      if: contains(matrix.repo, 'MPAS-Dev')
      run: |
        echo "nml_suffix=ncar"   >> $GITHUB_ENV
        echo "repo_name=mpasdev" >> $GITHUB_ENV

    - name: Configuration for ufs-community (baseline) tests.
      if: contains(matrix.repo, 'ufs-community')
      run: |
        echo "nml_suffix=gsl"         >> $GITHUB_ENV
        echo "repo_name=ufscommunity" >> $GITHUB_ENV

    - name: Display configuration
      run: |
        echo ${nml}
        echo ${nml_version}
        echo ${code_base}
        echo ${case_base}

     ##########################################################################################
     # Step 2a: Clone MPAS and build. (baselines)
     ##########################################################################################

    - name: Cache MPAS build (DEBUG; baselines)
      id: cache-mpas-bl-debug
      uses: actions/cache@v4
      with:
        path: ${mpas_bl_ROOT}
        key: cache-mpas-bl-debug-key

    - name: Checkout and build MPAS standalone for baseline generation (Debug)
      if: contains(matrix.build-type, 'Debug') && steps.cache-mpas-bl-debug.outputs.cache-hit != 'true'
      run: |
        cd ${runner_ROOT}
        git clone --recursive --branch ${{matrix.branch}} https://github.com/${{matrix.repo}}/MPAS-Model.git MPAS-Model-BL
        cd ${mpas_bl_ROOT}
        make ${{matrix.bld_target}} CORE=atmosphere DEBUG=true

    - name: Cache MPAS build (RELEASE; baselines)
      id: cache-mpas-bl-release
      uses: actions/cache@v4
      with:
        path: ${mpas_bl_ROOT}
        key: cache-mpas-bl-release-debug-key

    - name: Checkout and build MPAS standalone for baseline generation (Release)
      if: contains(matrix.build-type, 'Release') && steps.cache-mpas-bl-release.outputs.cache-hit != 'true'
      run: |
        cd ${runner_ROOT}
        git clone --recursive --branch ${{matrix.branch}} https://github.com/${{matrix.repo}}/MPAS-Model.git MPAS-Model-BL
        cd ${mpas_bl_ROOT}
        make ${{matrix.bld_target}} CORE=atmosphere

    ##########################################################################################
    # Step 2b: Clone MPAS and build (feature)
    ##########################################################################################
    - name: Checkout MPAS codebase for testing.
      uses: actions/checkout@v3

    - name: Initialize any submodules from testing codebase.
      run: |
        git config --global --add safe.directory ${MPAS_ROOT}
        cd ${MPAS_ROOT}
        git submodule update --init --recursive

    - name: Cache MPAS build (DEBUG; feature)
      id: cache-mpas-rt-debug
      uses: actions/cache@v4
      with:
        path: ${MPAS_ROOT}
        key: cache-mpas-rt-debug-key

    - name: Build MPAS standalone for testing (Debug)
      if: contains(matrix.build-type, 'Debug') && steps.cache-mpas-rt-debug.outputs.cache-hit != 'true'
      run: |
        cd ${MPAS_ROOT}
        make ${{matrix.bld_target}} CORE=atmosphere DEBUG=true

    - name: Cache MPAS build (RELEASE; feature)
      id: cache-mpas-rt-release
      uses: actions/cache@v4
      with:
        path: ${MPAS_ROOT}
        key: cache-mpas-rt-release-key

    - name: Build MPAS standalone for testing (Release)
      if: contains(matrix.build-type, 'Release') && steps.cache-mpas-rt-release.outputs.cache-hit != 'true'
      run: |
        cd ${MPAS_ROOT}
        make ${{matrix.bld_target}} CORE=atmosphere
